### ISSUE TITLE
Random non-triaged crashes

### ISSUE THREAD

**Issue by sergeylappo** [sergeylappo/boox-rapid-draw#6]
Issue to collect initial crashes information.
Since there's no observability whatsoever (app does not have access to web) this might get complicated. 

User 1:
> tried it in Google Classroom, annotating pdfs. And it works well, when it works.
> Sometimes the App would crash, and sometimes it would block all input except the drawing and then crash.

User 2
> I did find that it closed a few times (timed out?) and I had to go start the app up again.

**Comment by sergeylappo** [comment]
Managed to trigger one of the crashes
```
2024-10-23 23:48:52.901   527-527   lowmemorykiller         lmkd                                 I  Kill 'com.sergeylappo.booxrapiddraw' (12328), uid 10120, oom_score_adj 200 to free 11024kB rss, 38704kB swap; reason: device is not responding
2024-10-23 23:48:52.948  1431-2736  ActivityManager         system_server                        I  Process com.sergeylappo.booxrapiddraw (pid 12328) has died: prcp IMPF
2024-10-23 23:48:52.949  1431-1818  WindowManager           system_server                        I  WIN DEATH: Window{723df2f u0 com.sergeylappo.booxrapiddraw}
2024-10-23 23:48:52.949  1431-1818  InputManager-JNI        system_server                        W  Input channel object '723df2f com.sergeylappo.booxrapiddraw (client)' was disposed without first being removed with the input manager!
2024-10-23 23:48:52.966  1431-2736  ActivityManager         system_server                        W  Scheduling restart of crashed service com.sergeylappo.booxrapiddraw/.OverlayShowingService in 10842ms for start-requested
2024-10-23 23:48:53.592  1623-1966  PeopleSpaceWidgetMgr    com.android.systemui                 D  Sbn doesn't contain valid PeopleTileKey: null/0/com.sergeylappo.booxrapiddraw
2024-10-23 23:48:56.613  3642-3642  cr_RedirectHandler      org.chromium.chrome                  I  updateNewUrlLoading called (pageTransType: 8, isRedirect: false, hasUserGesture: true, lastUserInteractionTime: 131875149, lastCommittedEntryIndex: 0)
2024-10-23 23:49:03.831  1431-1470  ActivityManager         system_server                        I  Start proc 14841:com.sergeylappo.booxrapiddraw/u0a120 for service {com.sergeylappo.booxrapiddraw/com.sergeylappo.booxrapiddraw.OverlayShowingService}
2024-10-23 23:49:03.948  1431-2853  ActivityManager         system_server                        W  Stopping service due to app idle: u0a120 -18m48s131ms com.sergeylappo.booxrapiddraw/.OverlayShowingService
2024-10-23 23:49:04.473 14841-14841 GraphicsEnvironment     pid-14841                            V  ANGLE Developer option for 'com.sergeylappo.booxrapiddraw' set to: 'default'
2024-10-23 23:49:04.476 14841-14841 GraphicsEnvironment     pid-14841                            V  ANGLE GameManagerService for com.sergeylappo.booxrapiddraw: false
2024-10-23 23:49:05.014  1431-2853  ActivityManager         system_server                        W  Service done with onDestroy, but executeNesting=2: ServiceRecord{e3fead1 u0 com.sergeylappo.booxrapiddraw/.OverlayShowingService}
2024-10-23 23:49:05.027 14841-14841 AndroidRuntime          pid-14841                            E  FATAL EXCEPTION: main
                                                                                                    Process: com.sergeylappo.booxrapiddraw, PID: 14841
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.ViewParent.requestTransparentRegion(android.view.View)' on a null object reference
                                                                                                    	at android.view.SurfaceView.onAttachedToWindow(SurfaceView.java:315)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:20939)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2715)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2214)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8889)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1124)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:930)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:863)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1109)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8030)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
2024-10-23 23:49:13.118  1431-2853  ActivityManager         system_server                        I  Killing 14841:com.sergeylappo.booxrapiddraw/u0a120 (adj 905): crash
2024-10-23 23:49:13.127  1431-1455  InputManager-JNI        system_server                        W  Input channel object 'c10cc29 Application Error: com.sergeylappo.booxrapiddraw (client)' was disposed without first being removed with the input manager!
```

In short, it seems that app was killed due to OOM. 
The view was referenced after service destroy which caused null pointer 🤔

**Comment by sergeylappo** [comment]
Crash is no more, but the service won't restart automatically after the OOM
